### PR TITLE
Add labels required for IBM certification

### PR DESCRIPTION
**Pull request by mxpaspa**
Added required labels: 

```
  redhat.marketplace.com/name: redhat-marketplace-operator
  app.kubernetes.io/managed-by: OLM
  app.kubernetes.io/instance: default
```
to manifests and all objects created by the operator.

### CODE REVIEW

**Comment by dacleyra** [comment]
There are secondary objects that are not labeled

deployment.apps/rhm-remoteresources3-controller and it's pods
deployment.apps/rhm-watch-keeper and it's pods

The statefulset.apps/prometheus-rhm-marketplaceconfig-meterbase does not template label pod/prometheus-rhm-marketplaceconfig-meterbase

service/prometheus-operated 

```
---

oc get all
NAME                                                         READY   STATUS    RESTARTS   AGE
pod/prometheus-operator-6978799c8f-zbcvf                     3/3     Running   0          2m34s
pod/prometheus-rhm-marketplaceconfig-meterbase-0             6/6     Running   1          116s
pod/prometheus-rhm-marketplaceconfig-meterbase-1             6/6     Running   1          116s
pod/redhat-marketplace-controller-manager-5b6d8697d6-dmvqv   2/2     Running   0          3m8s
pod/rhm-metric-state-cf8b8bb89-945p9                         4/4     Running   0          2m34s
pod/rhm-remoteresources3-controller-77bbbbf65-kk4x8          2/2     Running   0          2m33s
pod/rhm-watch-keeper-5c48f9d649-2fwmb                        2/2     Running   0          2m32s

NAME                                                            TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)             AGE
service/prometheus-operated                                     ClusterIP   None             <none>        9090/TCP            116s
service/prometheus-operator                                     ClusterIP   None             <none>        8443/TCP,8080/TCP   2m34s
service/redhat-marketplace-controller-manager-metrics-service   ClusterIP   172.30.154.44    <none>        8443/TCP            3m9s
service/redhat-marketplace-controller-manager-service           ClusterIP   172.30.204.216   <none>        9443/TCP            3m8s
service/rhm-metric-state-service                                ClusterIP   172.30.249.177   <none>        9092/TCP,9093/TCP   2m34s
service/rhm-prometheus-meterbase                                ClusterIP   172.30.250.228   <none>        9091/TCP,9092/TCP   2m17s

NAME                                                    READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/prometheus-operator                     1/1     1            1           2m34s
deployment.apps/redhat-marketplace-controller-manager   1/1     1            1           3m8s
deployment.apps/rhm-metric-state                        1/1     1            1           2m34s
deployment.apps/rhm-remoteresources3-controller         1/1     1            1           2m33s
deployment.apps/rhm-watch-keeper                        1/1     1            1           2m33s

NAME                                                               DESIRED   CURRENT   READY   AGE
replicaset.apps/prometheus-operator-6978799c8f                     1         1         1       2m34s
replicaset.apps/redhat-marketplace-controller-manager-5b6d8697d6   1         1         1       3m8s
replicaset.apps/rhm-metric-state-cf8b8bb89                         1         1         1       2m34s
replicaset.apps/rhm-remoteresources3-controller-77bbbbf65          1         1         1       2m33s
replicaset.apps/rhm-watch-keeper-5c48f9d649                        1         1         1       2m33s

NAME                                                          READY   AGE
statefulset.apps/prometheus-rhm-marketplaceconfig-meterbase   2/2     116s


---

oc get all -l app.kubernetes.io/instance=default
NAME                                                         READY   STATUS    RESTARTS   AGE
pod/prometheus-operator-6978799c8f-zbcvf                     3/3     Running   0          3m1s
pod/redhat-marketplace-controller-manager-5b6d8697d6-dmvqv   2/2     Running   0          3m35s
pod/rhm-metric-state-cf8b8bb89-945p9                         4/4     Running   0          3m1s

NAME                                                            TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)             AGE
service/prometheus-operator                                     ClusterIP   None             <none>        8443/TCP,8080/TCP   3m1s
service/redhat-marketplace-controller-manager-metrics-service   ClusterIP   172.30.154.44    <none>        8443/TCP            3m36s
service/redhat-marketplace-controller-manager-service           ClusterIP   172.30.204.216   <none>        9443/TCP            3m35s
service/rhm-metric-state-service                                ClusterIP   172.30.249.177   <none>        9092/TCP,9093/TCP   3m1s
service/rhm-prometheus-meterbase                                ClusterIP   172.30.250.228   <none>        9091/TCP,9092/TCP   2m44s

NAME                                                    READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/prometheus-operator                     1/1     1            1           3m1s
deployment.apps/redhat-marketplace-controller-manager   1/1     1            1           3m35s
deployment.apps/rhm-metric-state                        1/1     1            1           3m1s

NAME                                                               DESIRED   CURRENT   READY   AGE
replicaset.apps/prometheus-operator-6978799c8f                     1         1         1       3m2s
replicaset.apps/redhat-marketplace-controller-manager-5b6d8697d6   1         1         1       3m36s
replicaset.apps/rhm-metric-state-cf8b8bb89                         1         1         1       3m2s

NAME                                                          READY   AGE
statefulset.apps/prometheus-rhm-marketplaceconfig-meterbase   2/2     2m24s

```

Some cm or secrets may have been overlooked as well?

```
oc get secret,configmap
NAME                                                                   TYPE                                  DATA   AGE
secret/builder-dockercfg-88z2z                                         kubernetes.io/dockercfg               1      30m
secret/builder-token-2djdd                                             kubernetes.io/service-account-token   4      30m
secret/builder-token-gqgfx                                             kubernetes.io/service-account-token   4      30m
secret/default-dockercfg-fkwfw                                         kubernetes.io/dockercfg               1      30m
secret/default-token-hrkbz                                             kubernetes.io/service-account-token   4      30m
secret/default-token-pxgz4                                             kubernetes.io/service-account-token   4      30m
secret/deployer-dockercfg-72zqg                                        kubernetes.io/dockercfg               1      30m
secret/deployer-token-c82gd                                            kubernetes.io/service-account-token   4      30m
secret/deployer-token-nprzn                                            kubernetes.io/service-account-token   4      30m
secret/kube-rbac-proxy                                                 Opaque                                1      9m36s
secret/prometheus-operator-tls                                         kubernetes.io/tls                     2      9m37s
secret/prometheus-rhm-marketplaceconfig-meterbase                      Opaque                                1      8m59s
secret/prometheus-rhm-marketplaceconfig-meterbase-tls-assets           Opaque                                0      8m59s
secret/redhat-marketplace-controller-manager-service                   kubernetes.io/tls                     2      10m
secret/redhat-marketplace-operator-dockercfg-ln968                     kubernetes.io/dockercfg               1      10m
secret/redhat-marketplace-operator-token-8fc4g                         kubernetes.io/service-account-token   4      10m
secret/redhat-marketplace-operator-token-jp7f2                         kubernetes.io/service-account-token   4      10m
secret/redhat-marketplace-prometheus-dockercfg-ckfmk                   kubernetes.io/dockercfg               1      10m
secret/redhat-marketplace-prometheus-operator-dockercfg-xx25t          kubernetes.io/dockercfg               1      10m
secret/redhat-marketplace-prometheus-operator-token-kqdk9              kubernetes.io/service-account-token   4      10m
secret/redhat-marketplace-prometheus-operator-token-l4jg2              kubernetes.io/service-account-token   4      10m
secret/redhat-marketplace-prometheus-token-8njls                       kubernetes.io/service-account-token   4      10m
secret/redhat-marketplace-prometheus-token-cdhlp                       kubernetes.io/service-account-token   4      10m
secret/redhat-marketplace-pull-secret                                  Opaque                                1      9m48s
secret/redhat-marketplace-remoteresources3deployment-dockercfg-vs7bg   kubernetes.io/dockercfg               1      10m
secret/redhat-marketplace-remoteresources3deployment-token-k9n4g       kubernetes.io/service-account-token   4      10m
secret/redhat-marketplace-remoteresources3deployment-token-nnlnt       kubernetes.io/service-account-token   4      10m
secret/redhat-marketplace-watch-keeper-dockercfg-w2chd                 kubernetes.io/dockercfg               1      10m
secret/redhat-marketplace-watch-keeper-token-ft5m7                     kubernetes.io/service-account-token   4      10m
secret/redhat-marketplace-watch-keeper-token-z7fr2                     kubernetes.io/service-account-token   4      10m
secret/rhm-cos-reader-key                                              Opaque                                1      9m36s
secret/rhm-meterbase-additional-scrape-configs                         Opaque                                1      9m36s
secret/rhm-meterbase-datasources                                       Opaque                                1      9m36s
secret/rhm-metric-state-tls                                            kubernetes.io/tls                     2      9m36s
secret/rhm-operator-secret                                             Opaque                                7      9m45s
secret/rhm-prometheus-meterbase-htpasswd                               Opaque                                1      9m33s
secret/rhm-prometheus-meterbase-proxy                                  Opaque                                1      9m36s
secret/rhm-prometheus-meterbase-tls                                    kubernetes.io/tls                     2      9m20s
secret/watch-keeper-secret                                             Opaque                                1      9m36s

NAME                                                               DATA   AGE
configmap/8fbe3a23.marketplace.redhat.com                          0      10m
configmap/kubelet-serving-ca-bundle                                1      9m33s
configmap/operator-certs-ca-bundle                                 1      9m37s
configmap/prometheus-rhm-marketplaceconfig-meterbase-rulefiles-0   0      8m59s
configmap/razee-cluster-metadata                                   1      9m36s
configmap/serving-certs-ca-bundle                                  1      10m
configmap/watch-keeper-config                                      2      9m36s
configmap/watch-keeper-limit-poll                                  0      9m36s
configmap/watch-keeper-non-namespaced                              1      9m36s
[dacleyra@greyjoy06 redhat-marketplace-operator]$
[dacleyra@greyjoy06 redhat-marketplace-operator]$
[dacleyra@greyjoy06 redhat-marketplace-operator]$
[dacleyra@greyjoy06 redhat-marketplace-operator]$ oc get secret,configmap -l redhat.marketplace.com/name=redhat-marketplace-operator
NAME                                             TYPE     DATA   AGE
secret/kube-rbac-proxy                           Opaque   1      9m57s
secret/rhm-meterbase-additional-scrape-configs   Opaque   1      9m57s
secret/rhm-meterbase-datasources                 Opaque   1      9m57s
secret/rhm-prometheus-meterbase-htpasswd         Opaque   1      9m54s
secret/rhm-prometheus-meterbase-proxy            Opaque   1      9m57s

NAME                                  DATA   AGE
configmap/kubelet-serving-ca-bundle   1      9m55s
configmap/operator-certs-ca-bundle    1      9m59s
configmap/serving-certs-ca-bundle     1      10m

```

**Review by dacleyra — COMMENTED** [review]
Some labeling opportunities may have been missed

**Comment by dacleyra** [comment]
Upon doing an install on top of a previous install, get

```
validatingwebhookconfiguration.admissionregistration.k8s.io/redhat-marketplace-validating-webhook-configuration configured
The Deployment "redhat-marketplace-controller-manager" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/instance":"default", "app.kubernetes.io/managed-by":"Helm", "redhat.marketplace.com/name":"redhat-marketplace-operator"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
make[1]: *** [install] Error 1
```

I'm slightly concerned an upgrade scenario might fail. Not sure if OLM removes the previous deployment, in order to apply the Deployment with an immutable field?

**Comment by mxpaspa** [comment]
Thanks @dacleyra I'll run over it again.

**Comment by mxpaspa** [comment]
@dacleyra Ah it looks like the objs that aren't labeled, don't use the base level factory functions. I.e. rrs3 deployment
```
func (f *Factory) NewRemoteResourceS3Deployment(instance *marketplacev1alpha1.RazeeDeployment) *appsv1.Deployment {
	var securityContext *corev1.PodSecurityContext
	if !f.operatorConfig.Infrastructure.HasOpenshift() {
		securityContext = &corev1.PodSecurityContext{
			FSGroup: ptr.Int64(1000),
		}
	}
	rep := ptr.Int32(1)
	maxSurge := intstr.FromString("25%")
	maxUnavailable := intstr.FromString("25%")

	return &appsv1.Deployment{
		ObjectMeta: metav1.ObjectMeta{
			Name:      utils.RHM_REMOTE_RESOURCE_S3_DEPLOYMENT_NAME,
			Namespace: f.namespace,
			Labels: map[string]string{
				"razee/watch-resource": "lite",
			},
		},
		...
```

**Comment by dacleyra** [comment]
Maybe a few more, if possible

pods annotated
service/prometheus-operated is not annotated
deployment.apps/rhm-watch-keeper is not annotated
replicaset.apps/rhm-remoteresources3-controller-77bbbbf65 is not annotated

```
oc get all -l app.kubernetes.io/instance=default
NAME                                                         READY   STATUS    RESTARTS   AGE
pod/prometheus-operator-6fc7cd547d-gvvf6                     3/3     Running   0          2m40s
pod/prometheus-rhm-marketplaceconfig-meterbase-0             6/6     Running   1          2m12s
pod/prometheus-rhm-marketplaceconfig-meterbase-1             6/6     Running   1          2m12s
pod/redhat-marketplace-controller-manager-68f568d6c4-jrblp   2/2     Running   0          24m
pod/rhm-metric-state-7c66cc9c9c-dkkf8                        4/4     Running   0          2m40s
pod/rhm-watch-keeper-774b45fbb8-ls4rn                        2/2     Running   0          2m32s

NAME                                                            TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)             AGE
service/prometheus-operator                                     ClusterIP   None             <none>        8443/TCP,8080/TCP   2m40s
service/redhat-marketplace-controller-manager-metrics-service   ClusterIP   172.30.10.32     <none>        8443/TCP            24m
service/redhat-marketplace-controller-manager-service           ClusterIP   172.30.58.60     <none>        9443/TCP            24m
service/rhm-metric-state-service                                ClusterIP   172.30.151.207   <none>        9092/TCP,9093/TCP   2m40s
service/rhm-prometheus-meterbase                                ClusterIP   172.30.148.89    <none>        9091/TCP,9092/TCP   2m29s

NAME                                                    READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/prometheus-operator                     1/1     1            1           2m40s
deployment.apps/redhat-marketplace-controller-manager   1/1     1            1           24m
deployment.apps/rhm-metric-state                        1/1     1            1           2m40s
deployment.apps/rhm-remoteresources3-controller         1/1     1            1           2m33s

NAME                                                               DESIRED   CURRENT   READY   AGE
replicaset.apps/prometheus-operator-6fc7cd547d                     1         1         1       2m40s
replicaset.apps/redhat-marketplace-controller-manager-68f568d6c4   1         1         1       24m
replicaset.apps/rhm-metric-state-7c66cc9c9c                        1         1         1       2m40s
replicaset.apps/rhm-watch-keeper-774b45fbb8                        1         1         1       2m32s

NAME                                                          READY   AGE
statefulset.apps/prometheus-rhm-marketplaceconfig-meterbase   2/2     2m12s
```

**Comment by mxpaspa** [comment]
thanks

**Comment by mxpaspa** [comment]
@dacleyra in my latest commit the rrs3 dep, watchkeeper dep, and meterbase pods should be getting labeled.

**Comment by mxpaspa** [comment]
@zach-source @dacleyra here is what I'm able to label without too much trouble. Keep in mind, everything for controller manager should get labeled in production, those resources aren't showing up here because we are using the helm wrapper for dev. Let me know if this will be good enough for cert. Thank you. 

**Pods:**
```
❯ kgp -l app.kubernetes.io/managed-by=OLM       
NAME                                               READY   STATUS    RESTARTS   AGE
prometheus-operator-57786696d-gk97n                3/3     Running   0          23m
prometheus-rhm-marketplaceconfig-meterbase-0       6/6     Running   1          23m
prometheus-rhm-marketplaceconfig-meterbase-1       6/6     Running   1          23m
rhm-metric-state-786dd6f697-whq5s                  4/4     Running   0          23m
rhm-remoteresources3-controller-5d6d5b8bf8-zwcgw   2/2     Running   0          23m
rhm-watch-keeper-85ccffb7fb-g2b4r                  2/2     Running   0          23m
```

**Deployments:**
```
❯ kgd -l app.kubernetes.io/managed-by=OLM               
NAME                              READY   UP-TO-DATE   AVAILABLE   AGE
prometheus-operator               1/1     1            1           25m
rhm-metric-state                  1/1     1            1           25m
rhm-remoteresources3-controller   1/1     1            1           25m
rhm-watch-keeper                  1/1     1            1           25m
```

**ReplicaSets**
```
❯ k get replicasets -l app.kubernetes.io/managed-by=OLM 
NAME                                         DESIRED   CURRENT   READY   AGE
prometheus-operator-57786696d                1         1         1       28m
rhm-metric-state-786dd6f697                  1         1         1       28m
rhm-remoteresources3-controller-5d6d5b8bf8   1         1         1       28m
rhm-watch-keeper-85ccffb7fb                  1         1         1       28m
```

**Services:**
```
❯ k get services -l app.kubernetes.io/managed-by=OLM 
NAME                       TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)             AGE
prometheus-operator        ClusterIP   None             <none>        8443/TCP,8080/TCP   25m
rhm-metric-state-service   ClusterIP   172.30.149.180   <none>        9092/TCP,9093/TCP   25m
rhm-prometheus-meterbase   ClusterIP   172.30.4.136     <none>        9091/TCP,9092/TCP   25m
```

**Secrets:**
```
❯ k get secrets -l app.kubernetes.io/managed-by=OLM  
NAME                                      TYPE     DATA   AGE
kube-rbac-proxy                           Opaque   1      25m
rhm-cos-reader-key                        Opaque   1      26m
rhm-meterbase-additional-scrape-configs   Opaque   1      26m
rhm-meterbase-datasources                 Opaque   1      26m
rhm-operator-secret                       Opaque   7      26m
rhm-prometheus-meterbase-htpasswd         Opaque   1      25m
rhm-prometheus-meterbase-proxy            Opaque   1      26m
watch-keeper-secret                       Opaque   1      26m
```

**ConfigMaps:**
```
❯ k get cm -l app.kubernetes.io/managed-by=OLM      
NAME                          DATA   AGE
kubelet-serving-ca-bundle     1      26m
operator-certs-ca-bundle      1      26m
razee-cluster-metadata        1      26m
serving-certs-ca-bundle       1      32m
watch-keeper-config           2      26m
watch-keeper-limit-poll       0      26m
watch-keeper-non-namespaced   1      26m
```

**Comment by zach-source** [comment]
Looks fine for first pass.

**Review by dacleyra — APPROVED** [review]
lgtm

**Review by dacleyra — APPROVED** [review]
lgtm

**Pull request merged**
