### PR TITLE
chore: enhancing integration tests to be modular

### PR DESCRIPTION
**Pull request by zach-source**

### CODE REVIEW

**Review by mxpaspa — COMMENTED** [review]
@zach-source I ran 'make code-gen`, `make setup-kind`, `make test-int-kind`. Looks like it's failing with: 

```
------------------------------
Failure [156.581 seconds]
[BeforeSuite] BeforeSuite 
/Users/maxpaspa@ibm.com/redhat-marketplace/redhat-marketplace-operator/test/integration/controller/controller_suite_test.go:59

  Unexpected error:
      <*errors.withStack | 0xc0006a41e0>: {
          error: {
              cause: {
                  ProcessState: {
                      pid: 30884,
                      status: 256,
                      rusage: {
                          Utime: {
                              Sec: 0,
                              Usec: 582193,
                              Pad_cgo_0: [0, 0, 0, 0],
                          },
                          Stime: {
                              Sec: 0,
                              Usec: 314045,
                              Pad_cgo_0: [0, 0, 0, 0],
                          },
                          Maxrss: 75227136,
                          Ixrss: 0,
                          Idrss: 0,
                          Isrss: 0,
                          Minflt: 41428,
                          Majflt: 5551,
                          Nswap: 0,
                          Inblock: 0,
                          Oublock: 0,
                          Msgsnd: 230,
                          Msgrcv: 246,
                          Nsignals: 215,
                          Nvcsw: 667,
                          Nivcsw: 18568,
                      },
                  },
                  Stderr: nil,
              },
              msg: "fail",
          },
          stack: [0x2b2d516, 0x2b2c609, 0x30c4f78, 0x15f271d, 0x15f2185, 0x15f2ada, 0x1637314, 0x1636b34, 0x163a5fa, 0x165191d, 0x1651526, 0x30c491a, 0x11f0303, 0x10b4b21],
      }
      fail: exit status 1
  occurred

  /Users/maxpaspa@ibm.com/go/pkg/mod/github.com/onsi/gomega@v1.10.1/internal/assertion/assertion.go:43

  Full Stack Trace
  github.com/onsi/gomega/internal/assertion.(*Assertion).ToNot(0xc0007e8140, 0x37a5aa0, 0x4578518, 0x0, 0x0, 0x0, 0x1)
  	/Users/maxpaspa@ibm.com/go/pkg/mod/github.com/onsi/gomega@v1.10.1/internal/assertion/assertion.go:43 +0x126
  github.com/redhat-marketplace/redhat-marketplace-operator/test/harness.(*TestHarness).Start(0xc0002c2f70, 0x37a5aa0, 0x4578518, 0xc000520050, 0x1)
  	/Users/maxpaspa@ibm.com/redhat-marketplace/redhat-marketplace-operator/test/harness/harness.go:130 +0x9a6
  github.com/redhat-marketplace/redhat-marketplace-operator/test/integration/controller_test.glob..func1()
  	/Users/maxpaspa@ibm.com/redhat-marketplace/redhat-marketplace-operator/test/integration/controller/controller_suite_test.go:75 +0x538
  github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync(0xc00057ee40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  	/Users/maxpaspa@ibm.com/go/pkg/mod/github.com/onsi/ginkgo@v1.13.0/internal/leafnodes/runner.go:113 +0xfd
  github.com/onsi/ginkgo/internal/leafnodes.(*runner).run(0xc00057ee40, 0xcdfe932, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  	/Users/maxpaspa@ibm.com/go/pkg/mod/github.com/onsi/ginkgo@v1.13.0/internal/leafnodes/runner.go:64 +0x125
  github.com/onsi/ginkgo/internal/leafnodes.(*simpleSuiteNode).Run(0xc0004bbb80, 0x1, 0x1, 0x0, 0x0, 0x2)
  	/Users/maxpaspa@ibm.com/go/pkg/mod/github.com/onsi/ginkgo@v1.13.0/internal/leafnodes/suite_nodes.go:25 +0xba
  github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runBeforeSuite(0xc000356c80, 0x0)
  	/Users/maxpaspa@ibm.com/go/pkg/mod/github.com/onsi/ginkgo@v1.13.0/internal/specrunner/spec_runner.go:123 +0x194
  github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).Run(0xc000356c80, 0x8)
  	/Users/maxpaspa@ibm.com/go/pkg/mod/github.com/onsi/ginkgo@v1.13.0/internal/specrunner/spec_runner.go:63 +0xd4
  github.com/onsi/ginkgo/internal/suite.(*Suite).Run(0xc0002480f0, 0x30e08b68, 0xc000001e00, 0x34bbd79, 0x18, 0xc0006905a0, 0x2, 0x2, 0x37bfe20, 0xc0002568c0, ...)
  	/Users/maxpaspa@ibm.com/go/pkg/mod/github.com/onsi/ginkgo@v1.13.0/internal/suite/suite.go:62 +0x6ba
  github.com/onsi/ginkgo.RunSpecsWithCustomReporters(0x37771a0, 0xc000001e00, 0x34bbd79, 0x18, 0xc000690520, 0x2, 0x2, 0x2)
  	/Users/maxpaspa@ibm.com/go/pkg/mod/github.com/onsi/ginkgo@v1.13.0/ginkgo_dsl.go:219 +0x35d
  github.com/onsi/ginkgo.RunSpecsWithDefaultAndCustomReporters(0x37771a0, 0xc000001e00, 0x34bbd79, 0x18, 0xc000690520, 0x1, 0x2, 0xc0001276c0)
  	/Users/maxpaspa@ibm.com/go/pkg/mod/github.com/onsi/ginkgo@v1.13.0/ginkgo_dsl.go:207 +0x126
  github.com/redhat-marketplace/redhat-marketplace-operator/test/integration/controller_test.TestEnv(0xc000001e00)
  	/Users/maxpaspa@ibm.com/redhat-marketplace/redhat-marketplace-operator/test/integration/controller/controller_suite_test.go:54 +0x29a
  testing.tRunner(0xc000001e00, 0x3579d48)
  	/usr/local/Cellar/go/1.15.3/libexec/src/testing/testing.go:1123 +0x203
  created by testing.(*T).Run
  	/usr/local/Cellar/go/1.15.3/libexec/src/testing/testing.go:1168 +0x5bc
```

**Comment by zach-source** [comment]
@mxpaspa can you re-review pls

**Comment by zach-source** [comment]
Retested and works reliably now. Also works on branch.

**Review by mxpaspa — APPROVED** [review]
Been using this for a few days now and seems work reliably.

**Pull request merged**
