### PR TITLE
updated go to version 1.17.10

### PR DESCRIPTION
**Pull request by ab-ibm**
Update go version to 1.17.10 to address vulnerabilities

### CODE REVIEW

**Comment by zach-source** [comment]
@dacleyra looks good to me, any concern about putting this in the release? We'll have to repackage it @MJSiddu heads up as well.

**Comment by dacleyra** [comment]
I think we are still building airgap on 1.16, and that should be 1.17

https://github.com/redhat-marketplace/redhat-marketplace-operator/blob/develop/airgap/v2/Dockerfile#L3

**Comment by zach-source** [comment]
@dacleyra Good catch Dan. Airgap could be a weird one cause of the dependencies it uses. May want to test thoroughly on 1.17 with it.

**Comment by dacleyra** [comment]
updated by another pr, closing

**Pull request closed without merging**
