### PR TITLE
support IEK without RHM account

### PR DESCRIPTION
**Pull request by jiangchen2019**
Changes include:
- https://github.ibm.com/symposium/track-and-plan/issues/28054
- https://github.ibm.com/symposium/track-and-plan/issues/28329

**Please note:** 
- Testing needs the production env because https://sandbox.marketplace.redhat.com/subscriptions/api/v1/keys/authentication returns 401 for any IEK
- ~~conMan will automatically generate RHM account when it receives a report file but RHM account does not exist. So please keep in mind when you test this PR, once there is a report file uploaded to conMan, the RHM account will be automatically generated. Your IEK will be changed from `without RHM account` to `with RHM account`. conMan team will change this behavior for MAS feature. https://github.ibm.com/symposium/track-and-plan/issues/27579~~
- If meterDefinition does not have metricType for meter, it will be treated as license type.
- commands to create ibm-entitlement-key secret and to check if the IEK has RHM account
 ```
oc create secret docker-registry ibm-entitlement-key -n  openshift-redhat-marketplace --docker-server=cp.icr.io --docker-username=cp --docker-password=<IEK>
```
```
curl -v --location  --request POST 'https://marketplace.redhat.com/subscriptions/api/v1/keys/authentication' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer <IEK>' \
--data-raw '{
	"createAccount": false,
	"sendEmailOnAccountCreation": false
}'
```
```
Create entitlement key: 
Production:
 https://myibm.ibm.com/products-services/containerlibrary
Stage:
https://wwwpoc.ibm.com/myibm/dashboard/containerlibrary
```
**test cases**
- IEK without RHM account (creating a new IBMid https://cloud.ibm.com/registration to get an IEK without RHM account and get an IEK at https://myibm.ibm.com/products-services/containerlibrary (production) or https://wwwpoc.ibm.com/myibm/dashboard/containerlibrary (stage))
-- check marketplaceconfig: spec.features.deployment is false, spec.features.registration is false, status.conditions includes RHMAccountExists type whose status is False
-- check RazeeDeploy rhm-marketplaceconfig-razeedeployment: spec.enabled: false, spec.features.deployment: false, spec.features.registration: false
-- make sure razee is not deployed
-- check meterdefinition prometheus-user-workload-uptime, rhm-meter-report-job-failed, and rhm-meter-state-uptime have `metricType: infrastructure`
-- run the following command in terminal. it should return 206 which means RHM/Software central account is not automatically created for the IEK
```
curl -v --location  --request POST 'https://marketplace.redhat.com/subscriptions/api/v1/keys/authentication' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer <IEK>' \
--data-raw '{
	"createAccount": false,
	"sendEmailOnAccountCreation": false
}'
```
-- check the generated report file only includes metric data for the infrastructure/adoption metric type meterdefinitions (temporally set isDisconnected to be true and then use datactl export pull to get the report file)
-- check the report file is uploaded in connected mode (set isDisconnected false). Check marketplaceconfig has status.conditions RHMAccountExists type whose status is still False

- IEK with RHM account
-- check marketplaceConfig: spec.features.deployment is true, spec.features.registration is true, status.conditions includes RHMAccountExists type whose status is True
-- check rhm-marketplaceconfig-razeedeployment: spec.enabled: true, spec.features.deployment: true, spec.features.registration: true
-- razee is correctly deployed
-- check the generated report file includes metric data for all metric type meterdefinitions (temporally set isDisconnected to be true and then use datactl export pull to get the report file)
-- check the report file is uploaded in connected mode (set isDisconnected false)

- Pull secret (regression testing)

### CODE REVIEW

**Comment by ab-ibm** [comment]
Code looks good but not able to test without dianemo changes to disable automatic account creation deployed in production env.

**Comment by jiangchen2019** [comment]
The E&R authentication url doesn't work correctly with IEK now. Reported this issue to E&R and om-account. https://cognitive-app.slack.com/archives/C020SJ6R6R4/p1677604775262629

**Comment by jiangchen2019** [comment]
Tested this PR with the conMan side changes. Works as expected.

**Comment by jiangchen2019** [comment]
> Code looks good but not able to test without dianemo changes to disable automatic account creation deployed in production env.

This PR has the logic to avoid calling dianemo when rhmAccountNotExist. So it works well without dianemo changes to disable automatic account creation deployed in production env.

**Comment by dacleyra** [comment]
This fires more often than necessary because both ClusterRegistration and MarketplaceConfig controllers call RhmAccountExists()
```
2023-06-08T15:36:18.596Z        INFO    marketplace     query to check rhmAccount existence     {"query": "https://marketplace.redhat.com/subscriptions/api/v1/keys/authentication"}
```
For MarketplaceConfig controller, we can first check the Condition in the same way as Reporter, and only call RhmAccountExists() if no status condition type is found

Since a user could register with IEK and then create an RHM account after, we should requeue the ClusterRegistration controller periodically, 24h maybe, let's consult with Lan on frequency
return reconcile.Result{RequeueAfter: time.Hour * 24}, nil

---

for IEK no RHM account case
in RegistrationStatus(), we are querying with an empty accountID
```
2023-06-08T15:37:01.214Z        INFO    marketplace     status query    {"query": "https://marketplace.redhat.com/provisioning/v1/registered-clusters?accountId=&uuid=5883fef1-5429-4883-83d6-5e6c4ed10891"}
```

This starts to touch on this debt item
https://github.ibm.com/symposium/track-and-plan/issues/29387


---
for IEK no RHM account case
in RegistrationStatus(), I think we are hitting this block and logging
```
	if resp.StatusCode != 200 {
		return RegistrationStatusOutput{
			RegistrationStatus: "HttpError",
			Err:                err,
			StatusCode:         resp.StatusCode,
		}, err
	}
```
```	
2023-06-08T15:37:01.199Z        INFO    controllers.MarketplaceConfig   attempting to update registration       {"func": "findRegistrationStatus", "Request.Namespace": "redhat-marketplace", "Request.Name": "marketplaceconfig", "status": "HttpError"}
```
HttpError is maybe not what want to present, or maybe we shouldn't be continuing to this without the accountID anyways

---

**Review by dacleyra — APPROVED** [review]

**Pull request merged**
