### PR TITLE
add identification labels to pods

### PR DESCRIPTION
**Pull request by dacleyra**

### CODE REVIEW

**Comment by dacleyra** [comment]
The current problem on upgrade is OLM's ability to update the deployment defined in the clusterserviceversion, we may need to rename the deployment, and verify the old deployment is also deleted.

Our controllers may have this problem as well, but we can think about modifying our factory CreateOrUpdate to have an intermediate delete if the immutable error is encountered, assuming we get a specific error.

```
I0203 22:03:31.024787       1 event.go:282] Event(v1.ObjectReference{Kind:"ClusterServiceVersion", Namespace:"openshift-redhat-marketplace", Name:"redhat-marketplace-operator.v2.10.0-beta.1304", UID:"8d732b2f-7701-4f16-8114-f29e1778eab4", APIVersion:"operators.coreos.com/v1alpha1", ResourceVersion:"189391077", FieldPath:""}): type: 'Warning' reason: 'InstallComponentFailed' install strategy failed: Deployment.apps "redhat-marketplace-controller-manager" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/instance":"rhm-deploying-operator", "app.kubernetes.io/managed-by":"ibm", "app.kubernetes.io/name":"red-hat-marketplace-deploying", "redhat.marketplace.com/name":"redhat-marketplace-operator"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
E0203 22:03:31.036603       1 queueinformer_operator.go:290] sync {"update" "openshift-redhat-marketplace/redhat-marketplace-operator.v2.10.0-beta.1304"} failed: error transitioning ClusterServiceVersion: Deployment.apps "redhat-marketplace-controller-manager" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/instance":"rhm-deploying-operator", "app.kubernetes.io/managed-by":"ibm", "app.kubernetes.io/name":"red-hat-marketplace-deploying", "redhat.marketplace.com/name":"redhat-marketplace-operator"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable and error updating CSV status: error updating ClusterServiceVersion status: Operation cannot be fulfilled on clusterserviceversions.operators.coreos.com "redhat-marketplace-operator.v2.10.0-beta.1304": the object has been modified; please apply your changes to the latest version and try again
```

@jiangchen2019

**Comment by dacleyra** [comment]
1. The labels aren't being set with the right guidance in mind

https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels

```
app.kubernetes.io/name: metric-state ; data-service; etc
app.kubernetes.io/instance: metric-state ; data-service; etc (we would not have -####, as we install as a singleton)
app.kubernetes.io/part-of: redhat-marketplace-deployer or redhat-marketplace-metering
app.kubernetes.io/managed-by: operator
```


2. matchLabels can not be changed, unless
- CSV changes the deployment name so that the deployment is deleted and recreated, there is a downstream problem with this deleting marketplaceconfig via ownerref
- factory is able to delete objects during CreateUpdate if an Invalid update on matchLabels is attempted

**Comment by jiangchen2019** [comment]
Tested the upgrade scenario, got two errors. 
One error is in metering controller, 

Reconciler error	{"controller": "marketplaceconfig", "controllerGroup": "marketplace.redhat.com", "controllerKind": "MarketplaceConfig", "marketplaceConfig": {"name":"marketplaceconfig","namespace":"openshift-redhat-marketplace"}, "namespace": "openshift-redhat-marketplace", "name": "marketplaceconfig", "reconcileID": "48e7ecd3-e28b-4578-ab3c-cc07955cdb31", "error": "**Object openshift-redhat-marketplace/marketplaceconfig is already owned by another Deployment controller redhat-marketplace-controller-manager**"}

The other error is in marketplaceconfig controller,

ERROR	Reconciler error	{"controller": "razeedeployment", "controllerGroup": "marketplace.redhat.com", "controllerKind": "RazeeDeployment", "razeeDeployment": {"name":"rhm-marketplaceconfig-razeedeployment","namespace":"openshift-redhat-marketplace"}, "namespace": "openshift-redhat-marketplace", "name": "rhm-marketplaceconfig-razeedeployment", "reconcileID": "d6a2d54d-752e-427c-ba77-af8ffaa2db59", "error": "**resource name may not be empty**"}

Since rhm-marketplaceconfig-razeedeployment could not been reconciled, rrs3 pod and watch-keeper pod were not recreated with the new labels.

**Comment by jiangchen2019** [comment]
> 



> Tested the upgrade scenario, got two errors. Since rhm-marketplaceconfig-razeedeployment could not been reconciled, rrs3 pod and watch-keeper pod were not recreated with the new labels.
> 
> **_One error is in metering controller,_**
> 
> Reconciler error {"controller": "marketplaceconfig", "controllerGroup": "marketplace.redhat.com", "controllerKind": "MarketplaceConfig", "marketplaceConfig": {"name":"marketplaceconfig","namespace":"openshift-redhat-marketplace"}, "namespace": "openshift-redhat-marketplace", "name": "marketplaceconfig", "reconcileID": "48e7ecd3-e28b-4578-ab3c-cc07955cdb31", "error": "**Object openshift-redhat-marketplace/marketplaceconfig is already owned by another Deployment controller redhat-marketplace-controller-manager**"}
> 
> **_The other error is in marketplaceconfig controller,_**
> 
> ERROR Reconciler error {"controller": "razeedeployment", "controllerGroup": "marketplace.redhat.com", "controllerKind": "RazeeDeployment", "razeeDeployment": {"name":"rhm-marketplaceconfig-razeedeployment","namespace":"openshift-redhat-marketplace"}, "namespace": "openshift-redhat-marketplace", "name": "rhm-marketplaceconfig-razeedeployment", "reconcileID": "d6a2d54d-752e-427c-ba77-af8ffaa2db59", "error": "**resource name may not be empty**"}

The marketplaceconfig ownerReference error was fixed. 

For the `resource name may not be empty` in RazeeDeployment reconciler, I checked it again with the above fix. I saw it repeated a few times in the deployer controller manager pod log, but then it was gone. The remoteresources3 controller pod and the watch-keeper pod were restarted and got the expected labels. So no fix is required

**Comment by dacleyra** [comment]
Changes are good for now, understanding that some changes will come with final name approval

**Review by jiangchen2019 — APPROVED** [review]

**Pull request merged**
