### PR TITLE
RemoteResourceS3 resources cleanup fix

### PR DESCRIPTION
**Pull request by mukulpanwar**

### CODE REVIEW

**Comment by zach-source** [comment]
@mxpaspa Can you verify this fix for me?

**Comment by mxpaspa** [comment]
> @mxpaspa Can you verify this fix for me?

sure thing.

**Comment by mxpaspa** [comment]
@mukulpanwar @zach-source Tested this out - seems to be working as expected.

**Review by mxpaspa — APPROVED** [review]
LGTM

**Pull request merged**
