### PR TITLE
add identification labels to pods

### PR DESCRIPTION
**Pull request by jiangchen2019**
https://github.ibm.com/symposium/track-and-plan/issues/19557

### CODE REVIEW

**Comment by ab-ibm** [comment]
@jiangchen2019 It's important to verify upgrade scenario here. As far I remember there was problem with upgrade after adding new labels

**Comment by jiangchen2019** [comment]
> @jiangchen2019 It's important to verify upgrade scenario here. As far I remember there was problem with upgrade after adding new labels

@ab-ibm this PR will be delivered to the split operator branch. Any suggestion on how to test upgrade scenario from combined operator to the split operators?

**Comment by dacleyra** [comment]
We'll retarget the PR, since we've merged splitOperator to develop. We can check the catalog from this branch build in an upgrade scenario, and see if it causes any issues.

**Comment by dacleyra** [comment]
moved branch to feature/addPodLabels targeted to develop, so full workflow will run

**Pull request closed without merging**
