### PR TITLE
Update reporter flow

### PR DESCRIPTION
**Pull request by MJSiddu**
**Tickets:**
https://zenhub.ibm.com/workspaces/symposium-workflow-5c49e21b79c5ae72931da0d6/issues/symposium/track-and-plan/25629
https://zenhub.ibm.com/workspaces/symposium-workflow-5c49e21b79c5ae72931da0d6/issues/symposium/track-and-plan/25827

**Changes:**
- Updated report uploader logic to solely depend on the status of the upload POST call
- Removed `statusRequest` function and other relevant components
- Updated/fixed unit tests
- Discussed with Mari, and removed conflict checks and retry checks from `checkError` logic 
- Updated upload task to delete the file from DataService only when the backend upload is successful.

### CODE REVIEW

**Review by ab-ibm — APPROVED** [review]

**Comment by ab-ibm** [comment]
Tested end to end flow with images 2.7.1-beta.1112 and data from LS. Verified usage data on Sandbox UI.

**Comment by MJSiddu** [comment]
@ab-ibm , FYI, the retry scenario still has some issues. Upon investigation, we noticed some unexpected bheaviours in the DataService module. So Dan is trying to identify that bug.

**Comment by dacleyra** [comment]
How to test the fix for the failure path

- Cause upload to intentionally fail by configuring DNS so that marketplace can not be resolved (after marketplaceconfig & registration)
```
apiVersion: operator.openshift.io/v1
kind: DNS
metadata:
  creationTimestamp: "2022-06-10T15:31:43Z"
  finalizers:
  - dns.operator.openshift.io/dns-controller
  generation: 2
  name: default
  resourceVersion: "32878076"
  uid: 8a86d191-aba2-4c6e-a29c-3ee39e2771ba
spec:
  nodePlacement: {}
  servers:
  - forwardPlugin:
      upstreams:
      - 0.0.0.0
    name: nosandbox
    zones:
    - sandbox.marketplace.redhat.com
```
- Generate a meterreport, or delete current meterreports and restart operator so they are recreated
- Set rhm-meter-report-upload cronjob to execute in the next 1-2 minutes
- rhm-meter-report-upload job runs, observe upload failure, observe meterereport status uploadAttempts increments
- Again, set rhm-meter-report-upload cronjob to execute in the next 1-2 minutes
- rhm-meter-report-upload job runs, check pod logs to see that the files List actually has a non-zero List, and has uploadAttempts metadata incremented
- Repeat until uploadAttempts: 3 max is reached
- After, the upload should not be attempted, but the files will be listed

**Review by dacleyra — APPROVED** [review]

**Comment by MJSiddu** [comment]
@dacleyra  - Tested all the scenarios. LGTM 👍

**Pull request merged**
